---
title: "Basic_Preprocessing"
output: html_document
---

# Why preprocess
## Prep practice space
### Slice data into training and testing

```{r }
library(caret)
library(kernlab)
data(spam)

inTrain<-createDataPartition(y=spam$type,p=0.75,list=FALSE)

training<-spam[inTrain,]
testing<-spam[-inTrain,]

hist(training$capitalAve,main="",xlab="ave. capital run length")

boxplot(training$capitalAve)
mean(training$capitalAve)
sd(training$capitalAve)

```

### Standardizing
```{r}
# z-score
trainCapAve<-training$capitalAve
trainCapAveZ<-(trainCapAve-mean(trainCapAve))/sd(trainCapAve)

mean(trainCapAveZ)
sd(trainCapAveZ)
boxplot(trainCapAveZ)

```

### Standardizing Test Set

### Standardizing - preProcess function
```{r}
preObj<-preProcess(training[,-58],method=c("center","scale"))

trainCapAveS<-predict(preObj,training[,-58])$capitalAve

mean(trainCapAveS)
sd(trainCapAveS)

testCapAveS<-predict(preObj,testing[,-58])$capitalAve
mean(testCapAveS)
sd(testCapAveS)
```

### Standardizing - Imputing Data
```{r}
set.seed(13343)

#Make some values NA
training$capAve<-training$capitalAve
selectNA<-rbinom(dim(training)[1],size=1,prob=0.05)==1
training$capAve[selectNA]<-NA

training$capAve

# Impute and standardize
preObj<-preProcess(training[,-58],method="knnImpute")
capAve<-predict(preObj,training[,-58])$capAve

capAve

# Standardize true values
capAveTruth<-training$capitalAve
capAveTruth<-(capAveTruth-mean(capAveTruth))/sd(capAveTruth)

capAveTruth

quantile(capAve - capAveTruth)
plot(quantile(capAve-capAveTruth))
```