---
title: "Caret_Practice"
output: html_document
---

```{r setup, echo=FALSE}
library(caret)
library(kernlab)
library(rpart)
library(gbm)
library(gam)
```
# Features
1. Some preprocessing - cleaning
2. Data splitting createDataPartition

## Learning Algorithms

### SPAM Example
### Data Splitting
```{r}
data(spam)
inTrain<-createDataPartition(y=spam$type,p=0.75,list=FALSE)
training<-spam[inTrain,]
testing<-spam[-inTrain,]
dim(training)
```

### Fit a model
```{r}
set.seed(32343)
modelFit<-train(type~.,data=training,method="glm")
modelFit
```

### Final Model
```{r}
#modelFit<-train(type~.,data=training,method="glm")
modelFit$finalModel
```

### Prediction
```{r}
predictions<-predict(modelFit,newdata=testing)
predictions
```

### Confusion Matrix
```{r}
confusionMatrix(predictions,testing$type)
```

### K-fold
```{r}
set.seed(32323)
folds<-createFolds(y=spam$type,k=10,
                   list=TRUE,returnTrain = TRUE)
sapply(folds,length)
```

### Resampling
```{r}
set.seed(32323)
folds<-createResample(y=spam$type,times=10,
                      list=TRUE)
sapply(folds,length)
```

### Time Slices
```{r}
set.seed(32323)
tme<-1:1000
folds<-createTimeSlices(y=tme,initialWindow = 20,
                        horizon = 10)

# initialWindow indicates the number of samples
# horizon represents the next x number of predicted values
names(folds)
```