---
title: "Plotting_Predictors"
output: html_document
---

```{r setup}
library(ISLR)
library(ggplot2)
library(caret)
library(Hmisc)
library(gridExtra)
data(Wage)
summary(Wage)
```

### Get training/test sets
```{r}
inTrain<-createDataPartition(y=Wage$wage,
                             p=0.7,list=FALSE)

training<-Wage[inTrain,]
testing<-Wage[-inTrain,]
dim(training); dim(testing)

```

### Feature plot
```{r}

featurePlot(x=training[,c("age","education","jobclass")], y=training$wage, plot="pairs")


```

### Qplot
```{r}
qplot(age,wage,data=training)

qplot(age,wage,colour=jobclass,data=training)

qq<-qplot(age,wage,colour=education,data=training)

qq+geom_smooth(method='lm',formula=y~x)
```

### cut2
```{r}
cutWage<-cut2(training$wage,g=3)
table(cutWage)

p1<-qplot(cutWage,age,data=training,fill=cutWage,
          geom=c("boxplot"))
p2<-qplot(cutWage,age,data=training,fill=cutWage,
          geom=c("boxplot","jitter"))

grid.arrange(p1,p2,ncol=2)

```

### Density plots
```{r}
qplot(wage,colour=education,data=training,
      geom="density")
```