---
title: "Random_Forest"
output: html_document
---

```{r setup}
library(caret)
library(ggplot2)
library(randomForest)
data(iris)

inTrain<-createDataPartition(y=iris$Species,
                             p=0.7,list=FALSE)

training<-iris[inTrain,]
testing<-iris[-inTrain,]

dim(training)
dim(testing)
```

```{r model fitting}
modFit<-train(Species~.,data=training,method="rf",prox=TRUE)
modFit
```

### Class "centers"
```{r plotting centers}
irisP<-classCenter(training[,c(3,4)],
                   training$Species,
                   modFit$finalModel$prox)
irisP<-as.data.frame(irisP)
irisP$Species<-rownames(irisP)

p<-qplot(Petal.Width,Petal.Length,col=Species,data=training)
p+geom_point(aes(x=Petal.Width,y=Petal.Length,col=Species),size=5,shape=4,data=irisP)
```

### Predicting new values
```{r predictions}
predictions<-predict(modFit,testing)
testing$predRight<-predictions==testing$Species
table(predictions,testing$Species)

qplot(Petal.Width,Petal.Length,colour=predRight,
      data=testing,
      main="newdata Predictions")
```